name: Deploy Astro to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 7 * * 1'   # rebuild semanal (lunes 07:00 UTC)
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Restore Astro cache
        uses: actions/cache@v4
        with:
          path: .astro-cache
          key: astro-${{ runner.os }}-${{ hashFiles('bun.lock') }}
          restore-keys: |
            astro-${{ runner.os }}- 

      - name: Build & Upload with Astro Action
        uses: withastro/action@v4
        with:
          package-manager: bun@latest

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
